---
version: "3.8"

services:
  foundry:
    hostname: ${FoundryVTTHostname}
    image: rhlowe/foundryvtt
    init: true
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/Data:/data
    environment:
      - CONTAINER_CACHE=/data/container_cache
      - CONTAINER_PATCHES=/data/container_patches
      # - CONTAINER_PATCH_URLS=
      #   https://raw.githubusercontent.com/felddy/...
      #   https://raw.githubusercontent.com/felddy/...
      - CONTAINER_PRESERVE_CONFIG=false
      - CONTAINER_PRESERVE_OWNER=^.*data.*$
      - CONTAINER_VERBOSE=true

      - FOUNDRY_ADMIN_KEY=${FoundryVTTAdminPassword}
      - FOUNDRY_LICENSE_KEY=${FoundryLicenseKey}
      - FOUNDRY_PASSWORD=${FoundryPassword}
      - FOUNDRY_USERNAME=${FoundryUsername}
      # - FOUNDRY_GID=foundry
      # - FOUNDRY_HOSTNAME=
      # - FOUNDRY_IP_DISCOVERY=
      # - FOUNDRY_LANGUAGE=
      # - FOUNDRY_LICENSE_KEY=
      # - FOUNDRY_LOCAL_HOSTNAME=
      # - FOUNDRY_MINIFY_STATIC_FILES=
      # - FOUNDRY_PASSWORD_SALT=
      # - FOUNDRY_PROTOCOL=
      # - FOUNDRY_PROXY_PORT=
      # - FOUNDRY_PROXY_SSL=false
      # - FOUNDRY_RELEASE_URL=
      # - FOUNDRY_ROUTE_PREFIX=
      # - FOUNDRY_SSL_CERT=
      # - FOUNDRY_SSL_KEY=
      # - FOUNDRY_UID=foundry
      # - FOUNDRY_UPNP_LEASE_DURATION=
      # - FOUNDRY_UPNP=false
      # - FOUNDRY_VERSION=10.286
      # - FOUNDRY_WORLD=
      # - TIMEZONE=US/Eastern
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
